import { useState } from 'react';
import { Pencil, Plus, Power, Trash2 } from 'lucide-react';
import { Catalogs, CatalogKind, CatalogItem } from '../lib/catalogs';
const labels:Record<CatalogKind,string>={secretarias:'Secretarias',unidades:'Unidades / Órgãos',equipes:'Equipes',tecnicos:'Técnicos',materiais:'Materiais'};
export default function Cadastros({catalogs,onChange,isAdmin}:{catalogs:Catalogs;onChange:(c:Catalogs)=>void;isAdmin:boolean}){
 const [kind,setKind]=useState<CatalogKind>('secretarias'); const items=catalogs[kind];
 const add=()=>{const name=prompt(`Nome - ${labels[kind]}`);if(!name)return;let parent='';let detail='';if(kind==='unidades')parent=prompt('Secretaria vinculada')||'';if(['equipes','tecnicos','materiais'].includes(kind))detail=prompt(kind==='materiais'?'Unidade de medida / detalhe':'Descrição / especialidade')||'';onChange({...catalogs,[kind]:[...items,{id:Date.now(),name,active:true,parent,detail}]})};
 const edit=(it:CatalogItem)=>{const name=prompt('Editar nome',it.name);if(!name)return;const detail=['equipes','tecnicos','materiais'].includes(kind)?prompt('Detalhe',it.detail||'')??it.detail:it.detail;const parent=kind==='unidades'?prompt('Secretaria vinculada',it.parent||'')??it.parent:it.parent;onChange({...catalogs,[kind]:items.map(x=>x.id===it.id?{...x,name,detail,parent}:x)})};
 const toggle=(it:CatalogItem)=>onChange({...catalogs,[kind]:items.map(x=>x.id===it.id?{...x,active:!x.active}:x)});
 const remove=(it:CatalogItem)=>{if(!isAdmin)return alert('Somente Admin pode excluir cadastros.');if(confirm(`Excluir definitivamente ${it.name}?`))onChange({...catalogs,[kind]:items.filter(x=>x.id!==it.id)})};
 return <><header className="topbar"><div><h1>Cadastros</h1><p>Base usada nas novas Ordens de Serviço.</p></div><button className="primary" onClick={add}><Plus size={18}/>Novo cadastro</button></header><div className="filters">{(Object.keys(labels) as CatalogKind[]).map(k=><button key={k} className={kind===k?'selected':''} onClick={()=>setKind(k)}>{labels[k]}</button>)}</div><section className="table-card"><div className="table-toolbar"><div><h2>{labels[kind]}</h2><p>Editar, inativar e excluir conforme permissão.</p></div></div><table><thead><tr><th>Nome</th><th>Vínculo / detalhe</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map(it=><tr key={it.id}><td><b>{it.name}</b></td><td>{it.parent||it.detail||'—'}</td><td>{it.active?'Ativo':'Inativo'}</td><td><div className="actions"><button onClick={()=>edit(it)}><Pencil size={14}/>Editar</button><button onClick={()=>toggle(it)}><Power size={14}/>{it.active?'Inativar':'Ativar'}</button>{isAdmin&&<button className="danger" onClick={()=>remove(it)}><Trash2 size={14}/>Excluir</button>}</div></td></tr>)}</tbody></table></section></>
}
