import { Plus, Search, AlertTriangle, PauseCircle, CheckCircle2, Clock3, Archive, Paperclip, ChevronRight } from 'lucide-react';
import { WorkOrder } from '../types';
export default function Dashboard({orders,onOpen}:{orders:WorkOrder[];onOpen:(id:number)=>void}){
 const cards=[['Abertas',orders.filter(x=>x.status==='ABERTA').length,Clock3],['Em andamento',orders.filter(x=>x.status==='EM_ANDAMENTO').length,Clock3],['Paralisadas',orders.filter(x=>x.status==='PARALISADA'||x.status==='AGUARDANDO_MATERIAL').length,PauseCircle],['Atendidas',orders.filter(x=>x.status==='ATENDIDA').length,CheckCircle2],['Atrasadas',orders.filter(x=>x.overdueDays>0).length,AlertTriangle],['Arquivadas',orders.filter(x=>x.archived).length,Archive]];
 return <><header className="topbar"><div><h1>Dashboard</h1><p>Visão operacional das Ordens de Serviço</p></div><button className="primary"><Plus size={18}/>Nova O.S.</button></header>
 <section className="cards">{cards.map(([label,value,Icon]:any)=><article className="metric" key={label}><div><span>{label}</span><strong>{value}</strong></div><Icon size={22}/></article>)}</section>
 <section className="chart-card"><div><h2>O.S. por mês</h2><p>Resumo rápido de abertura e conclusão</p></div><div className="bars">{[42,55,39,61,49,70,58,64].map((v,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:`${v}%`}}/><small>{['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago'][i]}</small></div>)}</div></section>
 <section className="table-card"><div className="table-toolbar"><div><h2>Ordens de Serviço</h2><p>Clique em uma O.S. para abrir a ficha completa.</p></div><div className="search"><Search size={17}/><input placeholder="Número, secretaria, unidade, serviço..."/></div></div>
 <div className="filters"><button className="selected">Todas</button><button>Abertas</button><button>Em andamento</button><button>Paralisadas</button><button>Atendidas</button><button>Atrasadas</button></div>
 <div className="table-scroll"><table><thead><tr><th>O.S.</th><th>Data</th><th>Secretaria / Unidade</th><th>Serviço</th><th>Equipe</th><th>Prazo / Tempo</th><th>Situação</th><th></th></tr></thead><tbody>{orders.map(os=><tr key={os.id} onClick={()=>onOpen(os.id)}><td><b>#{os.number}</b>{os.officeDocument&&<span className="sub"><Paperclip size={12}/>{os.officeDocument}</span>}</td><td>{new Date(os.openedAt+'T12:00:00').toLocaleDateString('pt-BR')}</td><td><b>{os.secretaria}</b><span className="sub">{os.unidade}</span></td><td><b>{os.serviceType}</b><span className="sub clamp">{os.description}</span></td><td>{os.team}</td><td><b>{new Date(os.deadline+'T12:00:00').toLocaleDateString('pt-BR')}</b><span className="sub">{os.estimatedAmount} {os.estimatedUnit.toLowerCase()}</span></td><td><span className={`status s-${os.status.toLowerCase()}`}>{os.status.replaceAll('_',' ')}</span>{os.overdueDays>0&&<span className="overdue">{os.overdueDays} dias atrasada</span>}</td><td><ChevronRight size={18}/></td></tr>)}</tbody></table></div></section></>
}
