import { useMemo, useState } from 'react';
import { BarChart3, Search, Printer, Clock3, MessageSquareText } from 'lucide-react';
import { WorkOrder } from '../types';

const monthLabels=['Todos','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
const dayMs=86400000;
function group(items:WorkOrder[],pick:(o:WorkOrder)=>string){const map=new Map<string,number>();for(const o of items){const key=(pick(o)||'Não informado').trim()||'Não informado';map.set(key,(map.get(key)||0)+1)}return [...map.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'pt-BR')).slice(0,10)}

export default function Reports({orders,onOpen}:{orders:WorkOrder[];onOpen:(id:number)=>void}){
  const years=useMemo(()=>{const values=orders.flatMap(o=>{if(!o.openedAt)return [];const d=new Date(o.openedAt+'T12:00:00');return Number.isFinite(d.getTime())?[d.getFullYear()]:[]});const unique=[...new Set(values)].sort((a,b)=>b-a);return unique.length?unique:[new Date().getFullYear()]},[orders]);
  const [year,setYear]=useState<number>(()=>years.includes(new Date().getFullYear())?new Date().getFullYear():years[0]);
  const [month,setMonth]=useState(0);const [status,setStatus]=useState('TODOS');const [q,setQ]=useState('');

  const filtered=useMemo(()=>orders.filter(o=>{if(!o.openedAt)return false;const d=new Date(o.openedAt+'T12:00:00');if(!Number.isFinite(d.getTime())||d.getFullYear()!==year)return false;if(month>0&&d.getMonth()!==month-1)return false;if(status==='ARQUIVADAS'&&!o.archived)return false;if(status!=='TODOS'&&status!=='ARQUIVADAS'&&o.status!==status)return false;const text=`${o.number} ${o.secretaria} ${o.unidade} ${o.serviceType} ${o.description} ${o.team}`.toLowerCase();return text.includes(q.trim().toLowerCase())}),[orders,year,month,status,q]);
  const active=filtered.filter(o=>!o.archived);const attended=filtered.filter(o=>o.status==='ATENDIDA'||o.status==='CONCLUIDA').length;const pending=active.filter(o=>['ABERTA','EM_ANDAMENTO','PARALISADA','AGUARDANDO_MATERIAL'].includes(o.status)).length;const late=active.filter(o=>o.overdueDays>0).length;
  const serviceRate=filtered.length?Math.round((attended/filtered.length)*100):0;
  const messageCount=filtered.reduce((s,o)=>s+(o.history||[]).filter(h=>h.kind==='MENSAGEM').length,0);
  const chargeCount=filtered.reduce((s,o)=>s+(o.history||[]).filter(h=>h.kind==='MENSAGEM'&&h.messageKind==='ATRASO').length,0);
  const plannedDays=filtered.map(o=>{const a=new Date(o.openedAt+'T12:00:00').getTime(),b=new Date(o.deadline+'T12:00:00').getTime();return Number.isFinite(a)&&Number.isFinite(b)&&b>=a?Math.round((b-a)/dayMs):null}).filter((v):v is number=>v!==null);
  const avgPlanned=plannedDays.length?Math.round(plannedDays.reduce((a,b)=>a+b,0)/plannedDays.length):0;
  const bySecretary=group(filtered,o=>o.secretaria),byUnit=group(filtered,o=>o.unidade),byTeam=group(filtered,o=>o.team),byService=group(filtered,o=>o.serviceType);
  const maxGroup=Math.max(1,...bySecretary.map(x=>x[1]),...byTeam.map(x=>x[1]),...byService.map(x=>x[1]));

  const GroupTable=({title,rows}:{title:string;rows:[string,number][]})=><article className="panel"><div className="panel-title"><h3>{title}</h3><span>{rows.length} grupo(s)</span></div>{rows.length===0?<p className="hint">Sem dados no período.</p>:rows.map(([name,count])=><div key={name} style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:10,alignItems:'center',padding:'8px 0',borderBottom:'1px solid #edf2ee'}}><div style={{minWidth:0}}><b style={{display:'block',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}} title={name}>{name}</b><div style={{height:5,background:'#edf2ee',borderRadius:99,marginTop:5,overflow:'hidden'}}><i style={{display:'block',height:'100%',width:`${Math.max(4,(count/maxGroup)*100)}%`,background:'var(--green-700)',borderRadius:99}}/></div></div><strong>{count}</strong></div>)}</article>;

  return <>
    <header className="topbar"><div><h1>Relatórios</h1><p>Indicadores administrativos e consolidação das Ordens de Serviço</p></div><button onClick={()=>window.print()}><Printer size={17}/>Imprimir</button></header>
    <section className="table-card"><div className="table-toolbar"><div><h2>Filtros do relatório</h2><p>Selecione período, situação e pesquisa.</p></div></div><div className="filters" style={{alignItems:'center',gap:10,flexWrap:'wrap'}}><select value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y} value={y}>{y}</option>)}</select><select value={month} onChange={e=>setMonth(Number(e.target.value))}>{monthLabels.map((m,i)=><option key={m} value={i}>{m}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="TODOS">Todas as situações</option><option value="ABERTA">Abertas</option><option value="EM_ANDAMENTO">Em andamento</option><option value="PARALISADA">Paralisadas</option><option value="AGUARDANDO_MATERIAL">Aguardando material</option><option value="ATENDIDA">Atendidas</option><option value="CONCLUIDA">Concluídas</option><option value="CANCELADA">Canceladas</option><option value="ARQUIVADAS">Arquivadas</option></select><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Número, secretaria, unidade, serviço..."/></div></div></section>
    <section className="cards"><article className="metric"><div><span>Total no período</span><strong>{filtered.length}</strong></div><BarChart3 size={22}/></article><article className="metric"><div><span>Atendidas / concluídas</span><strong>{attended}</strong></div><BarChart3 size={22}/></article><article className="metric"><div><span>Pendentes</span><strong>{pending}</strong></div><Clock3 size={22}/></article><article className="metric"><div><span>Atrasadas</span><strong>{late}</strong></div><Clock3 size={22}/></article><article className="metric"><div><span>Taxa de atendimento</span><strong>{serviceRate}%</strong></div><BarChart3 size={22}/></article><article className="metric"><div><span>Prazo médio planejado</span><strong>{avgPlanned} dias</strong></div><Clock3 size={22}/></article><article className="metric"><div><span>Mensagens registradas</span><strong>{messageCount}</strong></div><MessageSquareText size={22}/></article><article className="metric"><div><span>Cobranças de atraso</span><strong>{chargeCount}</strong></div><MessageSquareText size={22}/></article></section>
    <section className="content-grid"><GroupTable title="O.S. por secretaria" rows={bySecretary}/><GroupTable title="O.S. por unidade" rows={byUnit}/><GroupTable title="O.S. por equipe / empresa" rows={byTeam}/><GroupTable title="O.S. por tipo de serviço" rows={byService}/></section>
    <section className="table-card"><div className="table-toolbar"><div><h2>O.S. encontradas</h2><p>{filtered.length} registro(s) no filtro selecionado.</p></div></div><div className="table-scroll"><table><thead><tr><th>O.S.</th><th>Data</th><th>Secretaria / Unidade</th><th>Serviço</th><th>Equipe</th><th>Prazo</th><th>Status</th><th>Mensagens</th></tr></thead><tbody>{filtered.slice().sort((a,b)=>b.number-a.number||(b.openedAt||'').localeCompare(a.openedAt||'')).map(os=><tr key={os.id} onClick={()=>onOpen(os.id)} style={{cursor:'pointer'}}><td><b>#{os.number}</b></td><td>{new Date(os.openedAt+'T12:00:00').toLocaleDateString('pt-BR')}</td><td><b>{os.secretaria}</b><span className="sub">{os.unidade}</span></td><td><b>{os.serviceType}</b><span className="sub clamp">{os.description}</span></td><td>{os.team}</td><td>{new Date(os.deadline+'T12:00:00').toLocaleDateString('pt-BR')}{os.overdueDays>0&&<span className="overdue">{os.overdueDays} dias</span>}</td><td><span className={`status s-${os.status.toLowerCase()}`}>{os.status.replaceAll('_',' ')}</span>{os.archived&&<span className="sub">Arquivada</span>}</td><td>{(os.history||[]).filter(h=>h.kind==='MENSAGEM').length}</td></tr>)}{filtered.length===0&&<tr><td colSpan={8} style={{textAlign:'center',padding:28}}>Nenhuma O.S. encontrada para este filtro.</td></tr>}</tbody></table></div></section>
  </>;
}
