import { ArrowLeft, Pencil, Archive, Trash2, Printer, Share2, Plus, Camera, FileText, Clock3, Package, Users, MessageSquareText } from 'lucide-react';
import { WorkOrder } from '../types';
export default function WorkOrderDetail({os,onBack}:{os:WorkOrder;onBack:()=>void}){
 return <><header className="topbar"><div className="title-row"><button className="icon-btn" onClick={onBack}><ArrowLeft size={20}/></button><div><h1>O.S. {os.number}</h1><p>{os.secretaria} • {os.unidade}{os.local?` • ${os.local}`:''}</p></div></div><div className="actions"><button><Pencil size={16}/>Editar</button><button><Archive size={16}/>Arquivar</button><button><Printer size={16}/>Imprimir</button><button><Share2 size={16}/>Gerar resumo</button><button className="danger"><Trash2 size={16}/>Excluir</button></div></header>
 <section className="detail-hero"><div><span className={`status s-${os.status.toLowerCase()}`}>{os.status.replaceAll('_',' ')}</span><h2>{os.serviceType}</h2><p>{os.description}</p></div><div className="progress-box"><div><span>Progresso</span><strong>{os.progress}%</strong></div><div className="progress-track"><i style={{width:`${os.progress}%`}}/></div><small>{os.overdueDays>0?`Atrasada há ${os.overdueDays} dias`:'Dentro do prazo'}</small></div></section>
 <section className="detail-grid"><article><span>Data de abertura</span><strong>{new Date(os.openedAt+'T12:00:00').toLocaleDateString('pt-BR')}</strong></article><article><span>Prazo</span><strong>{new Date(os.deadline+'T12:00:00').toLocaleDateString('pt-BR')}</strong></article><article><span>Tempo previsto</span><strong>{os.estimatedAmount} {os.estimatedUnit.toLowerCase()}</strong></article><article><span>Equipe</span><strong>{os.team}</strong><small>{os.workforceOrigin}</small></article></section>
 <div className="tabs"><button className="active">Resumo</button><button>Andamentos</button><button>Fotos e arquivos</button><button>Materiais</button><button>Mão de obra</button><button>Histórico</button><button>Encerramento</button></div>
 <section className="content-grid"><article className="panel"><div className="panel-title"><h3>Informações da O.S.</h3><button><Pencil size={15}/>Editar</button></div><dl><dt>Secretaria</dt><dd>{os.secretaria}</dd><dt>Unidade</dt><dd>{os.unidade}</dd><dt>Local</dt><dd>{os.local||'—'}</dd><dt>Ofício</dt><dd>{os.officeDocument||'Sem ofício vinculado'}</dd><dt>Prioridade</dt><dd>{os.priority}</dd><dt>Atendida</dt><dd>{os.attended?'Sim':'Não'}</dd></dl></article>
 <article className="panel"><div className="panel-title"><h3>Materiais</h3><button><Plus size={15}/>Adicionar</button></div><p>{os.materialsSummary}</p><div className="mini-row"><Package size={17}/><span>Cadastro estruturado por quantidade/unidade</span></div></article>
 <article className="panel wide"><div className="panel-title"><h3>Fotos e documentos</h3><button><Plus size={15}/>Anexar</button></div><div className="attachment-summary"><div><Camera/><strong>Antes</strong><span>2 fotos</span></div><div><Camera/><strong>Durante</strong><span>3 fotos</span></div><div><Camera/><strong>Final</strong><span>1 foto</span></div><div><FileText/><strong>Documentos</strong><span>2 arquivos</span></div></div><p className="hint">Fotos, prints de conversa, ofícios, notas fiscais, comprovantes, orçamentos e outros arquivos ficam vinculados exclusivamente a esta O.S.</p></article>
 <article className="panel"><div className="panel-title"><h3>Andamento recente</h3><button><Plus size={15}/>Registrar</button></div><div className="timeline"><div><Clock3/><p><b>30/08/2026 09:45</b><br/>Equipe realizou vistoria inicial.</p></div><div><MessageSquareText/><p><b>30/08/2026 14:20</b><br/>Identificada necessidade de material complementar.</p></div></div></article>
 <article className="panel"><div className="panel-title"><h3>Mão de obra</h3><button><Plus size={15}/>Lançar</button></div><div className="mini-row"><Users size={18}/><div><b>{os.team}</b><span>{os.estimatedAmount} {os.estimatedUnit.toLowerCase()} previstas</span></div></div></article></section></>
}
