import { useState } from 'react';
import { ArrowLeft, Save } from 'lucide-react';
import { WorkOrder } from '../types';
export default function WorkOrderForm({initial,number,onCancel,onSave}:{initial?:WorkOrder;number:number;onCancel:()=>void;onSave:(os:WorkOrder)=>void}){
 const [f,setF]=useState<WorkOrder>(initial??{id:Date.now(),number,openedAt:new Date().toISOString().slice(0,10),secretaria:'',unidade:'',local:'',serviceType:'',description:'',team:'Equipe Própria',workforceOrigin:'Mão de obra própria',priority:'MEDIA',deadline:new Date().toISOString().slice(0,10),estimatedAmount:1,estimatedUnit:'DIARIAS',status:'ABERTA',progress:10,attended:false,archived:false,materialsSummary:'',notesCount:0,attachmentsCount:0,officeDocument:'',overdueDays:0,observations:'',attachments:[]});
 const set=(k:keyof WorkOrder,v:any)=>setF(x=>({...x,[k]:v}));
 const submit=(e:any)=>{e.preventDefault();if(!f.secretaria||!f.unidade||!f.serviceType||!f.description){alert('Preencha Secretaria, Unidade, Tipo de serviço e Descrição.');return;}onSave(f)};
 const inputStyle={width:'100%',padding:'10px',border:'1px solid #d0d5dd',borderRadius:8,font:'inherit'};
 return <><header className="topbar"><div className="title-row"><button className="icon-btn" onClick={onCancel}><ArrowLeft size={20}/></button><div><h1>{initial?'Editar':'Nova'} O.S. #{f.number}</h1><p>Cadastro completo da Ordem de Serviço</p></div></div></header><form onSubmit={submit} className="panel" style={{maxWidth:1100}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:14}}>
 {([['Data','openedAt','date'],['Secretaria','secretaria','text'],['Unidade / Órgão','unidade','text'],['Local / Setor','local','text'],['Tipo de serviço','serviceType','text'],['Equipe','team','text'],['Origem da mão de obra','workforceOrigin','text'],['Prazo','deadline','date'],['Ofício / Documento','officeDocument','text']] as any[]).map(([label,key,type])=><label key={key}><span>{label}</span><input style={inputStyle} type={type} value={(f as any)[key]||''} onChange={e=>set(key,e.target.value)}/></label>)}
 <label><span>Prioridade</span><select style={inputStyle} value={f.priority} onChange={e=>set('priority',e.target.value)}><option>BAIXA</option><option>MEDIA</option><option>ALTA</option><option>URGENTE</option></select></label>
 <label><span>Tempo previsto</span><input style={inputStyle} type="number" min="0" step="0.5" value={f.estimatedAmount} onChange={e=>set('estimatedAmount',Number(e.target.value))}/></label>
 <label><span>Unidade de tempo</span><select style={inputStyle} value={f.estimatedUnit} onChange={e=>set('estimatedUnit',e.target.value)}><option value="HORAS">Horas</option><option value="DIARIAS">Diárias</option></select></label></div>
 <label style={{display:'block',marginTop:14}}><span>Descrição do serviço</span><textarea style={{...inputStyle,minHeight:110}} value={f.description} onChange={e=>set('description',e.target.value)}/></label>
 <label style={{display:'block',marginTop:14}}><span>Materiais previstos/utilizados</span><textarea style={{...inputStyle,minHeight:80}} value={f.materialsSummary} onChange={e=>set('materialsSummary',e.target.value)}/></label>
 <label style={{display:'block',marginTop:14}}><span>Observações</span><textarea style={{...inputStyle,minHeight:80}} value={f.observations||''} onChange={e=>set('observations',e.target.value)}/></label>
 {initial&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginTop:14}}><label><span>Status</span><select style={inputStyle} value={f.status} onChange={e=>set('status',e.target.value)}>{['ABERTA','EM_ANDAMENTO','PARALISADA','AGUARDANDO_MATERIAL','ATENDIDA','CONCLUIDA','CANCELADA'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Progresso (%)</span><input style={inputStyle} type="number" min="0" max="100" value={f.progress} onChange={e=>set('progress',Number(e.target.value))}/></label></div>}
 <div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:20}}><button type="button" className="icon-btn" onClick={onCancel}>Cancelar</button><button className="primary" type="submit"><Save size={18}/>Salvar O.S.</button></div></form></>}
