import { useState } from 'react';
import { ArrowLeft, Save } from 'lucide-react';
import { WorkOrder } from '../types';
import { Catalogs } from '../lib/catalogs';
export default function WorkOrderForm({initial,number,onCancel,onSave,catalogs}:{initial?:WorkOrder;number:number;onCancel:()=>void;onSave:(os:WorkOrder)=>void;catalogs:Catalogs}){
 const [f,setF]=useState<WorkOrder>(initial??{id:Date.now(),number,openedAt:new Date().toISOString().slice(0,10),secretaria:'',unidade:'',local:'',serviceType:'',description:'',team:'Equipe Própria',workforceOrigin:'Mão de obra própria',priority:'MEDIA',deadline:new Date().toISOString().slice(0,10),estimatedAmount:1,estimatedUnit:'DIARIAS',status:'ABERTA',progress:10,attended:false,archived:false,materialsSummary:'',notesCount:0,attachmentsCount:0,officeDocument:'',overdueDays:0,observations:'',attachments:[]});
 const set=(k:keyof WorkOrder,v:any)=>setF(x=>({...x,[k]:v}));
 const units=catalogs.unidades.filter(x=>x.active&&(!f.secretaria||x.parent===f.secretaria));
 const active=(key:keyof Catalogs)=>catalogs[key].filter(x=>x.active);
 const submit=(e:any)=>{e.preventDefault();if(!f.secretaria||!f.unidade||!f.serviceType||!f.description){alert('Preencha Secretaria, Unidade, Tipo de serviço e Descrição.');return;}onSave(f)};
 const inputStyle={width:'100%',padding:'10px',border:'1px solid #d0d5dd',borderRadius:8,font:'inherit'};
 return <><header className="topbar"><div className="title-row"><button className="icon-btn" onClick={onCancel}><ArrowLeft size={20}/></button><div><h1>{initial?'Editar':'Nova'} O.S. #{f.number}</h1><p>Cadastro completo da Ordem de Serviço</p></div></div></header><form onSubmit={submit} className="panel" style={{maxWidth:1100}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:14}}>
 <label><span>Data</span><input style={inputStyle} type="date" value={f.openedAt} onChange={e=>set('openedAt',e.target.value)}/></label>
 <label><span>Secretaria</span><select style={inputStyle} value={f.secretaria} onChange={e=>{setF(x=>({...x,secretaria:e.target.value,unidade:'',local:''}))}}><option value="">Selecione</option>{active('secretarias').map(x=><option key={x.id}>{x.name}</option>)}</select></label>
 <label><span>Unidade / Órgão</span><select style={inputStyle} value={f.unidade} onChange={e=>{const unit=catalogs.unidades.find(x=>x.name===e.target.value&&(!f.secretaria||x.parent===f.secretaria));setF(x=>({...x,unidade:e.target.value,local:unit?.address||''}))}}><option value="">Selecione</option>{units.map(x=><option key={x.id}>{x.name}</option>)}</select></label>
 <label><span>Local / Setor</span><input style={inputStyle} value={f.local||''} onChange={e=>set('local',e.target.value)} placeholder="Endereço da unidade; complemente com sala/setor se necessário"/></label>
 <label><span>Tipo de serviço</span><input style={inputStyle} value={f.serviceType} onChange={e=>set('serviceType',e.target.value)} placeholder="Elétrica, Hidráulica, Pintura..."/></label>
 <label><span>Equipe</span><select style={inputStyle} value={f.team} onChange={e=>{const team=catalogs.equipes.find(x=>x.name===e.target.value);setF(x=>({...x,team:e.target.value,workforceOrigin:team?.detail||x.workforceOrigin}))}}>{active('equipes').map(x=><option key={x.id}>{x.name}</option>)}</select></label>
 <label><span>Origem da mão de obra</span><input style={inputStyle} value={f.workforceOrigin} onChange={e=>set('workforceOrigin',e.target.value)}/></label>
 <label><span>Prazo</span><input style={inputStyle} type="date" value={f.deadline} onChange={e=>set('deadline',e.target.value)}/></label>
 <label><span>Ofício / Documento</span><input style={inputStyle} value={f.officeDocument||''} onChange={e=>set('officeDocument',e.target.value)}/></label>
 <label><span>Prioridade</span><select style={inputStyle} value={f.priority} onChange={e=>set('priority',e.target.value)}><option>BAIXA</option><option>MEDIA</option><option>ALTA</option><option>URGENTE</option></select></label>
 <label><span>Tempo previsto</span><input style={inputStyle} type="number" min="0" step="0.5" value={f.estimatedAmount} onChange={e=>set('estimatedAmount',Number(e.target.value))}/></label>
 <label><span>Unidade de tempo</span><select style={inputStyle} value={f.estimatedUnit} onChange={e=>set('estimatedUnit',e.target.value)}><option value="HORAS">Horas</option><option value="DIARIAS">Diárias</option></select></label></div>
 <label style={{display:'block',marginTop:14}}><span>Descrição do serviço</span><textarea style={{...inputStyle,minHeight:110}} value={f.description} onChange={e=>set('description',e.target.value)}/></label>
 <label style={{display:'block',marginTop:14}}><span>Materiais previstos/utilizados</span><textarea style={{...inputStyle,minHeight:80}} value={f.materialsSummary} onChange={e=>set('materialsSummary',e.target.value)} placeholder={active('materiais').map(x=>`${x.name} (${x.detail||'un'})`).join(' • ')}/></label>
 <label style={{display:'block',marginTop:14}}><span>Observações</span><textarea style={{...inputStyle,minHeight:80}} value={f.observations||''} onChange={e=>set('observations',e.target.value)}/></label>
 {initial&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginTop:14}}><label><span>Status</span><select style={inputStyle} value={f.status} onChange={e=>set('status',e.target.value)}>{['ABERTA','EM_ANDAMENTO','PARALISADA','AGUARDANDO_MATERIAL','ATENDIDA','CONCLUIDA','CANCELADA'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Progresso (%)</span><input style={inputStyle} type="number" min="0" max="100" value={f.progress} onChange={e=>set('progress',Number(e.target.value))}/></label></div>}
 <div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:20}}><button type="button" className="icon-btn" onClick={onCancel}>Cancelar</button><button className="primary" type="submit"><Save size={18}/>Salvar O.S.</button></div></form></>}
