import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Building2, CheckCircle2, ChevronRight, CirclePause, Clock3, ExternalLink, FileText, HardHat, Image as ImageIcon, Paperclip, Plus, Ruler, Save, Search, Trash2, WalletCards } from 'lucide-react';
import { deleteDesktopAttachment, isDesktopMode, loadDesktopSnapshot, openDesktopAttachment, readDesktopAttachment, saveDesktopAttachment, saveDesktopSnapshot, SNAPSHOT_WORKS } from '../lib/nativeDb';

type WorkStatus='NAO_INICIADA'|'EM_ANDAMENTO'|'PARALISADA'|'ATRASADA'|'CONCLUIDA'|'CANCELADA';
type WorkArea='EXECUTIVO'|'SAUDE'|'EDUCACAO'|'OUTRA';
type MeasurementStatus='RASCUNHO'|'APROVADA'|'CANCELADA';
type DocumentKind='CONTRATO'|'PROJETO'|'MEDICAO'|'FOTO'|'ADITIVO'|'OUTRO';
interface Measurement{id:number;number:number;date:string;period:string;value:number;status:MeasurementStatus;notes?:string}
interface WorkDocument{id:string;name:string;type:string;kind:DocumentKind;createdAt:string;sizeBytes:number;dataUrl?:string;storedPath?:string}
interface WorkUpdate{id:number;date:string;text:string;progress?:number}
interface WorkRecord{
 id:number;name:string;area:WorkArea;address:string;object:string;
 company:string;cnpj:string;contractNumber:string;originalValue:number;
 startDate:string;expectedEndDate:string;technicalResponsible:string;inspector:string;
 status:WorkStatus;physicalProgress:number;measurements:Measurement[];
 documents:WorkDocument[];updates:WorkUpdate[];createdAt:string;updatedAt:string;
}

const STORAGE='sos-works-v2';
const LEGACY_STORAGE='sos-works-v1';
const STATUS_LABELS:Record<WorkStatus,string>={NAO_INICIADA:'Não iniciada',EM_ANDAMENTO:'Em andamento',PARALISADA:'Paralisada',ATRASADA:'Atrasada',CONCLUIDA:'Concluída',CANCELADA:'Cancelada'};
const AREA_LABELS:Record<WorkArea,string>={EXECUTIVO:'Executivo',SAUDE:'Saúde',EDUCACAO:'Educação',OUTRA:'Outra'};
const DOC_LABELS:Record<DocumentKind,string>={CONTRATO:'Contrato',PROJETO:'Projeto',MEDICAO:'Medição',FOTO:'Foto',ADITIVO:'Aditivo',OUTRO:'Outro arquivo'};
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const today=()=>new Date().toISOString().slice(0,10);
const brDate=(v?:string)=>v?new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const validArea=(v:any):WorkArea=>['EXECUTIVO','SAUDE','EDUCACAO','OUTRA'].includes(v)?v:'EXECUTIVO';
const validStatus=(v:any):WorkStatus=>['NAO_INICIADA','EM_ANDAMENTO','PARALISADA','ATRASADA','CONCLUIDA','CANCELADA'].includes(v)?v:'NAO_INICIADA';
const normalizeMeasurement=(m:any):Measurement=>({id:Number(m?.id)||Date.now(),number:Number(m?.number)||1,date:String(m?.date||today()),period:String(m?.period||''),value:Number(m?.value)||0,status:m?.status==='CANCELADA'?'CANCELADA':m?.status==='RASCUNHO'?'RASCUNHO':'APROVADA',notes:String(m?.notes||'')});
const normalizeWork=(w:any):WorkRecord=>({
 id:Number(w?.id)||Date.now(),name:String(w?.name||''),area:validArea(w?.area),address:String(w?.address||w?.location||''),object:String(w?.object||''),
 company:String(w?.company||''),cnpj:String(w?.cnpj||''),contractNumber:String(w?.contractNumber||''),originalValue:Number(w?.originalValue)||0,
 startDate:String(w?.startDate||today()),expectedEndDate:String(w?.expectedEndDate||''),technicalResponsible:String(w?.technicalResponsible||''),inspector:String(w?.inspector||''),
 status:validStatus(w?.status),physicalProgress:Math.max(0,Math.min(100,Number(w?.physicalProgress)||0)),measurements:Array.isArray(w?.measurements)?w.measurements.map(normalizeMeasurement):[],
 documents:Array.isArray(w?.documents)?w.documents:[],updates:Array.isArray(w?.updates)?w.updates:[],createdAt:String(w?.createdAt||new Date().toISOString()),updatedAt:String(w?.updatedAt||new Date().toISOString())
});
function loadLocal():WorkRecord[]{try{const raw=localStorage.getItem(STORAGE)||localStorage.getItem(LEGACY_STORAGE);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed.map(normalizeWork):[]}catch{return []}}
function saveLocal(items:WorkRecord[]){try{localStorage.setItem(STORAGE,JSON.stringify(items));localStorage.removeItem(LEGACY_STORAGE);return true}catch{return false}}
function blankWork():WorkRecord{return {id:Date.now(),name:'',area:'EXECUTIVO',address:'',object:'',company:'',cnpj:'',contractNumber:'',originalValue:0,startDate:today(),expectedEndDate:'',technicalResponsible:'',inspector:'',status:'NAO_INICIADA',physicalProgress:0,measurements:[],documents:[],updates:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function fileToDataUrl(file:File):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function humanSize(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`}
const statusClass=(status:WorkStatus)=>status==='EM_ANDAMENTO'?'s-em_andamento':status==='CONCLUIDA'?'s-concluida':status==='PARALISADA'?'s-paralisada':status==='ATRASADA'?'s-cancelada':status==='CANCELADA'?'s-cancelada':'s-aberta';

export default function Works({isAdmin}:{isAdmin:boolean}){
 const desktop=isDesktopMode();
 const [works,setWorks]=useState<WorkRecord[]>(()=>loadLocal());
 const [selected,setSelected]=useState<number|null>(null);
 const [editing,setEditing]=useState<WorkRecord|null>(null);
 const [newMeasurement,setNewMeasurement]=useState(false);
 const [q,setQ]=useState('');
 const [filter,setFilter]=useState<'TODAS'|WorkStatus>('TODAS');

 useEffect(()=>{if(!desktop)return;let cancelled=false;(async()=>{const saved=await loadDesktopSnapshot<any[]>(SNAPSHOT_WORKS);if(cancelled)return;if(saved){const fixed=saved.map(normalizeWork);setWorks(fixed);saveLocal(fixed);await saveDesktopSnapshot(SNAPSHOT_WORKS,fixed)}else if(works.length)await saveDesktopSnapshot(SNAPSHOT_WORKS,works)})();return()=>{cancelled=true}},[]);
 const persist=async(next:WorkRecord[])=>{if(desktop&&!await saveDesktopSnapshot(SNAPSHOT_WORKS,next)){alert('Não foi possível salvar as obras no banco SQLite do HD externo.');return false}if(!saveLocal(next)){alert('Não foi possível atualizar o armazenamento local de apoio.');return false}setWorks(next);return true};
 const metrics=useMemo(()=>[
  ['Obras cadastradas',works.length,Building2],['Em andamento',works.filter(x=>x.status==='EM_ANDAMENTO').length,HardHat],['Paralisadas',works.filter(x=>x.status==='PARALISADA').length,CirclePause],['Atrasadas',works.filter(x=>x.status==='ATRASADA').length,Clock3],['Concluídas',works.filter(x=>x.status==='CONCLUIDA').length,CheckCircle2],['Medições',works.reduce((s,w)=>s+w.measurements.length,0),WalletCards],
 ] as const,[works]);
 const visible=useMemo(()=>works.filter(w=>`${w.name} ${w.address} ${w.company} ${w.contractNumber} ${AREA_LABELS[w.area]}`.toLowerCase().includes(q.toLowerCase())&&(filter==='TODAS'||w.status===filter)),[works,q,filter]);
 const current=works.find(x=>x.id===selected)||null;

 if(editing)return <WorkForm initial={editing} onCancel={()=>setEditing(null)} onSave={async item=>{const exists=works.some(x=>x.id===item.id);const next=exists?works.map(x=>x.id===item.id?item:x):[item,...works];if(await persist(next)){setEditing(null);setSelected(item.id)}}}/>;
 if(current)return <WorkDetail work={current} isAdmin={isAdmin} onBack={()=>setSelected(null)} onEdit={()=>setEditing({...current})} newMeasurement={newMeasurement} setNewMeasurement={setNewMeasurement} onSave={async item=>{if(await persist(works.map(x=>x.id===item.id?item:x)))setSelected(item.id)}}/>;

 return <>
  <header className="topbar"><div><h1>Obras</h1><p>Acompanhamento institucional de obras, contratos e execução física.</p></div>{isAdmin&&<button className="primary" type="button" onClick={()=>setEditing(blankWork())}><Plus size={18}/>Nova obra</button>}</header>
  <section className="cards">{metrics.map(([label,value,Icon])=><article className="metric" key={label}><div><span>{label}</span><strong>{value}</strong></div><Icon size={22}/></article>)}</section>
  <section className="table-card"><div className="table-toolbar"><div><h2>Obras cadastradas</h2><p>Consulta geral das obras. Somente ADMIN pode cadastrar ou alterar informações.</p></div><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Obra, endereço, empresa, contrato..."/></div></div><div className="filters">{([['TODAS','Todas'],['NAO_INICIADA','Não iniciadas'],['EM_ANDAMENTO','Em andamento'],['PARALISADA','Paralisadas'],['ATRASADA','Atrasadas'],['CONCLUIDA','Concluídas']] as const).map(([v,l])=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{l}</button>)}</div>
  {visible.length===0?<div style={{padding:36,textAlign:'center'}}><HardHat size={34} style={{marginBottom:10,opacity:.45}}/><h3 style={{margin:'0 0 6px'}}>{works.length?'Nenhuma obra encontrada':'Nenhuma obra cadastrada'}</h3><p style={{margin:0}}>{works.length?'Altere a busca ou os filtros para localizar uma obra.':'Cadastre a primeira obra para iniciar o acompanhamento.'}</p></div>:<div className="table-scroll"><table><thead><tr><th>Obra</th><th>Área</th><th>Empresa</th><th>Contrato</th><th>Prazo</th><th>Situação</th><th>Avanço</th><th>Medições</th><th></th></tr></thead><tbody>{visible.map(w=><tr key={w.id} onClick={()=>setSelected(w.id)}><td><b>{w.name}</b><span className="sub">{w.address||'Endereço não informado'}</span></td><td>{AREA_LABELS[w.area]}</td><td>{w.company||'—'}</td><td>{w.contractNumber||'—'}</td><td>{brDate(w.expectedEndDate)}</td><td><span className={`status ${statusClass(w.status)}`}>{STATUS_LABELS[w.status]}</span></td><td><b>{w.physicalProgress}%</b><span className="sub">execução física</span></td><td>{w.measurements.length}</td><td><ChevronRight size={18}/></td></tr>)}</tbody></table></div>}</section>
 </>;
}

function WorkForm({initial,onCancel,onSave}:{initial:WorkRecord;onCancel:()=>void;onSave:(w:WorkRecord)=>void}){
 const [f,setF]=useState<WorkRecord>(normalizeWork(initial));const set=(k:keyof WorkRecord,v:any)=>setF(x=>({...x,[k]:v}));
 const submit=(e:FormEvent)=>{e.preventDefault();const missing:string[]=[];if(!f.name.trim())missing.push('Nome da obra');if(!f.company.trim())missing.push('Empresa contratada');if(!f.contractNumber.trim())missing.push('Número do contrato');if(!f.object.trim())missing.push('Objeto/descrição');if(missing.length){alert(`Ainda falta preencher: ${missing.join(', ')}.`);return}onSave({...f,updatedAt:new Date().toISOString()})};
 return <><header className="topbar"><div className="title-row"><button className="icon-btn" onClick={onCancel}><ArrowLeft size={20}/></button><div><h1>{initial.name?'Editar obra':'Nova obra'}</h1><p>Cadastro e acompanhamento da obra.</p></div></div></header><form className="works-form" onSubmit={submit}>
  <section className="panel"><div className="panel-title"><div><h3>Identificação da obra</h3><p className="hint">Informações principais e situação atual.</p></div></div><div className="form-grid"><label><span>Nome da obra</span><input value={f.name} onChange={e=>set('name',e.target.value)}/></label><label><span>Área</span><select value={f.area} onChange={e=>set('area',e.target.value as WorkArea)}><option value="EXECUTIVO">Executivo</option><option value="SAUDE">Saúde</option><option value="EDUCACAO">Educação</option><option value="OUTRA">Outra</option></select></label><label><span>Endereço</span><input value={f.address} onChange={e=>set('address',e.target.value)}/></label><label><span>Status</span><select value={f.status} onChange={e=>set('status',e.target.value as WorkStatus)}>{Object.entries(STATUS_LABELS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div></section>
  <section className="panel" style={{marginTop:16}}><div className="panel-title"><div><h3>Contrato e empresa</h3><p className="hint">Dados essenciais da contratação.</p></div></div><div className="form-grid"><label><span>Empresa contratada</span><input value={f.company} onChange={e=>set('company',e.target.value)}/></label><label><span>CNPJ</span><input value={f.cnpj} onChange={e=>set('cnpj',e.target.value)}/></label><label><span>Número do contrato</span><input value={f.contractNumber} onChange={e=>set('contractNumber',e.target.value)}/></label><label><span>Valor original</span><input type="number" min="0" step="0.01" value={f.originalValue} onChange={e=>set('originalValue',Number(e.target.value))}/></label></div></section>
  <section className="panel" style={{marginTop:16}}><div className="panel-title"><div><h3>Execução e fiscalização</h3><p className="hint">Prazos, responsáveis e percentual de execução física.</p></div></div><div className="form-grid"><label><span>Data de início</span><input type="date" value={f.startDate} onChange={e=>set('startDate',e.target.value)}/></label><label><span>Previsão de término</span><input type="date" value={f.expectedEndDate} onChange={e=>set('expectedEndDate',e.target.value)}/></label><label><span>Avanço físico (%)</span><input type="number" min="0" max="100" value={f.physicalProgress} onChange={e=>set('physicalProgress',Math.max(0,Math.min(100,Number(e.target.value))))}/></label><label><span>Responsável técnico</span><input value={f.technicalResponsible} onChange={e=>set('technicalResponsible',e.target.value)}/></label><label><span>Fiscal da obra</span><input value={f.inspector} onChange={e=>set('inspector',e.target.value)}/></label></div><label style={{display:'block',marginTop:14}}><span>Objeto / descrição da obra</span><textarea value={f.object} onChange={e=>set('object',e.target.value)} style={{minHeight:110}}/></label></section>
  <div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:18}}><button type="button" onClick={onCancel}>Cancelar</button><button className="primary" type="submit"><Save size={18}/>Salvar obra</button></div>
 </form></>;
}

function WorkDetail({work,isAdmin,onBack,onEdit,newMeasurement,setNewMeasurement,onSave}:{work:WorkRecord;isAdmin:boolean;onBack:()=>void;onEdit:()=>void;newMeasurement:boolean;setNewMeasurement:(v:boolean)=>void;onSave:(w:WorkRecord)=>void}){
 const fileRef=useRef<HTMLInputElement>(null);const [docKind,setDocKind]=useState<DocumentKind>('OUTRO');const [addingUpdate,setAddingUpdate]=useState(false);
 const addDocument=async(file:File|null)=>{if(!file)return;const max=isDesktopMode()?10*1024*1024:2*1024*1024;if(file.size>max){alert(`Arquivo acima do limite de ${isDesktopMode()?'10 MB':'2 MB'}.`);return}try{const dataUrl=await fileToDataUrl(file);const id=crypto.randomUUID();let storedPath:string|undefined;if(isDesktopMode()){const base64=dataUrl.split(',')[1]||'';const saved=await saveDesktopAttachment(work.id,id,file.name,file.type||'application/octet-stream',base64);if(!saved){alert('Não foi possível salvar o arquivo no HD externo.');return}storedPath=saved}const doc:WorkDocument={id,name:file.name,type:file.type||'application/octet-stream',kind:docKind,createdAt:new Date().toISOString(),sizeBytes:file.size,storedPath,dataUrl:isDesktopMode()?undefined:dataUrl};onSave({...work,documents:[...work.documents,doc],updatedAt:new Date().toISOString()})}catch{alert('Não foi possível anexar o arquivo.')}finally{if(fileRef.current)fileRef.current.value=''}};
 const openDocument=async(doc:WorkDocument)=>{if(isDesktopMode()&&doc.storedPath){if(!await openDesktopAttachment(doc.storedPath))alert('Não foi possível abrir o arquivo no programa padrão do Windows.');return}let src=doc.dataUrl||'';if(!src&&doc.storedPath)src=await readDesktopAttachment(doc.storedPath,doc.type)||'';if(!src){alert('Arquivo não encontrado.');return}const win=window.open(src,'_blank');if(!win)alert('Não foi possível abrir o arquivo nesta versão.')};
 const removeDocument=async(doc:WorkDocument)=>{if(!isAdmin)return;if(!confirm(`Excluir o arquivo "${doc.name}" desta obra?`))return;if(doc.storedPath&&!await deleteDesktopAttachment(doc.storedPath)){alert('Não foi possível excluir o arquivo físico.');return}onSave({...work,documents:work.documents.filter(x=>x.id!==doc.id),updatedAt:new Date().toISOString()})};
 const removeMeasurement=(id:number)=>{if(!isAdmin)return;const m=work.measurements.find(x=>x.id===id);if(!m||!confirm(`Excluir a medição nº ${m.number}?`))return;onSave({...work,measurements:work.measurements.filter(x=>x.id!==id),updatedAt:new Date().toISOString()})};
 return <><header className="topbar"><div className="title-row"><button className="icon-btn" onClick={onBack}><ArrowLeft size={20}/></button><div><h1>{work.name}</h1><p>{AREA_LABELS[work.area]} • Contrato {work.contractNumber||'—'}</p></div></div>{isAdmin&&<div style={{display:'flex',gap:8}}><button onClick={onEdit}>Editar obra</button><button className="primary" onClick={()=>setNewMeasurement(true)}><Plus size={18}/>Nova medição</button></div>}</header>
 <section className="cards"><article className="metric"><div><span>Status</span><strong style={{fontSize:18}}>{STATUS_LABELS[work.status]}</strong></div><HardHat size={22}/></article><article className="metric"><div><span>Avanço físico</span><strong>{work.physicalProgress}%</strong></div><Ruler size={22}/></article><article className="metric"><div><span>Medições</span><strong>{work.measurements.length}</strong></div><WalletCards size={22}/></article><article className="metric"><div><span>Documentos</span><strong>{work.documents.length}</strong></div><FileText size={22}/></article></section>
 <section className="detail-grid"><article className="panel"><h3>Dados da obra</h3><p><b>Área:</b> {AREA_LABELS[work.area]}</p><p><b>Endereço:</b> {work.address||'—'}</p><p><b>Empresa:</b> {work.company||'—'}</p><p><b>CNPJ:</b> {work.cnpj||'—'}</p><p><b>Responsável técnico:</b> {work.technicalResponsible||'—'}</p><p><b>Fiscal:</b> {work.inspector||'—'}</p><p><b>Objeto:</b> {work.object||'—'}</p></article><article className="panel"><h3>Contrato e prazos</h3><p><b>Contrato:</b> {work.contractNumber||'—'}</p><p><b>Valor original:</b> {money.format(work.originalValue)}</p><p><b>Início:</b> {brDate(work.startDate)}</p><p><b>Previsão de término:</b> {brDate(work.expectedEndDate)}</p><p><b>Status:</b> {STATUS_LABELS[work.status]}</p><p><b>Execução física:</b> {work.physicalProgress}%</p></article></section>
 <section className="table-card"><div className="table-toolbar"><div><h2>Medições</h2><p>Registro técnico das medições da obra, sem controle de pagamento.</p></div></div>{work.measurements.length===0?<div style={{padding:24}}>Nenhuma medição cadastrada.</div>:<div className="table-scroll"><table><thead><tr><th>Nº</th><th>Data</th><th>Período</th><th>Valor</th><th>Status</th><th>Observações</th>{isAdmin&&<th>Ações</th>}</tr></thead><tbody>{work.measurements.map(m=><tr key={m.id}><td><b>{m.number}</b></td><td>{brDate(m.date)}</td><td>{m.period||'—'}</td><td>{money.format(m.value)}</td><td>{m.status}</td><td>{m.notes||'—'}</td>{isAdmin&&<td><button className="icon-btn" title="Excluir medição" onClick={()=>removeMeasurement(m.id)}><Trash2 size={16}/></button></td>}</tr>)}</tbody></table></div>}</section>
 {newMeasurement&&isAdmin&&<MeasurementForm nextNumber={work.measurements.reduce((n,m)=>Math.max(n,m.number),0)+1} onCancel={()=>setNewMeasurement(false)} onSave={m=>{onSave({...work,measurements:[...work.measurements,m],updatedAt:new Date().toISOString()});setNewMeasurement(false)}}/>}
 <section className="table-card" style={{marginTop:18}}><div className="table-toolbar"><div><h2>Documentos, fotos e aditivos</h2><p>Contrato, projetos, medições, fotos, aditivos e demais arquivos da obra.</p></div>{isAdmin&&<div style={{display:'flex',gap:8,alignItems:'center'}}><select value={docKind} onChange={e=>setDocKind(e.target.value as DocumentKind)}>{Object.entries(DOC_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="primary" onClick={()=>fileRef.current?.click()}><Paperclip size={17}/>Anexar arquivo</button><input ref={fileRef} hidden type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx" onChange={e=>addDocument(e.target.files?.[0]||null)}/></div>}</div>{work.documents.length===0?<div style={{padding:24}}>Nenhum arquivo anexado.</div>:<div className="cards" style={{padding:16}}>{work.documents.map(doc=><article className="metric" key={doc.id} style={{minWidth:220}}><div style={{minWidth:0}}><span>{DOC_LABELS[doc.kind]}</span><strong style={{fontSize:14,wordBreak:'break-word'}}>{doc.name}</strong><small>{humanSize(doc.sizeBytes)}</small><div style={{display:'flex',gap:6,marginTop:10}}><button type="button" onClick={()=>openDocument(doc)}><ExternalLink size={15}/>Abrir</button>{isAdmin&&<button type="button" onClick={()=>removeDocument(doc)}><Trash2 size={15}/>Excluir</button>}</div></div>{doc.kind==='FOTO'?<ImageIcon size={22}/>:<FileText size={22}/>}</article>)}</div>}</section>
 <section className="table-card" style={{marginTop:18}}><div className="table-toolbar"><div><h2>Andamentos da obra</h2><p>Histórico cronológico das atualizações de execução e percentual físico.</p></div>{isAdmin&&<button onClick={()=>setAddingUpdate(true)}><Plus size={17}/>Novo andamento</button>}</div>{work.updates.length===0?<div style={{padding:24}}>Nenhum andamento registrado.</div>:<div style={{padding:16}}>{[...work.updates].sort((a,b)=>b.date.localeCompare(a.date)).map(u=><article className="panel" key={u.id} style={{marginBottom:10}}><b>{brDate(u.date)}</b>{typeof u.progress==='number'&&<span> • Avanço físico: {u.progress}%</span>}<p style={{marginBottom:0}}>{u.text}</p></article>)}</div>}{addingUpdate&&isAdmin&&<UpdateForm currentProgress={work.physicalProgress} onCancel={()=>setAddingUpdate(false)} onSave={u=>{onSave({...work,physicalProgress:typeof u.progress==='number'?u.progress:work.physicalProgress,updates:[...work.updates,u],updatedAt:new Date().toISOString()});setAddingUpdate(false)}}/>}</section></>;
}

function MeasurementForm({nextNumber,onCancel,onSave}:{nextNumber:number;onCancel:()=>void;onSave:(m:Measurement)=>void}){
 const [m,setM]=useState<Measurement>({id:Date.now(),number:nextNumber,date:today(),period:'',value:0,status:'RASCUNHO',notes:''});const set=(k:keyof Measurement,v:any)=>setM(x=>({...x,[k]:v}));const submit=(e:FormEvent)=>{e.preventDefault();if(m.number<=0||m.value<=0){alert('Informe número e valor válidos para a medição.');return}onSave(m)};return <section className="panel" style={{marginTop:18}}><div className="panel-title"><h3>Nova medição</h3><button onClick={onCancel}>Cancelar</button></div><form onSubmit={submit} className="form-grid"><label><span>Número</span><input type="number" min="1" value={m.number} onChange={e=>set('number',Number(e.target.value))}/></label><label><span>Data</span><input type="date" value={m.date} onChange={e=>set('date',e.target.value)}/></label><label><span>Período</span><input value={m.period} onChange={e=>set('period',e.target.value)} placeholder="Ex.: agosto/2026"/></label><label><span>Valor da medição</span><input type="number" min="0" step="0.01" value={m.value} onChange={e=>set('value',Number(e.target.value))}/></label><label><span>Status</span><select value={m.status} onChange={e=>set('status',e.target.value as MeasurementStatus)}><option value="RASCUNHO">Rascunho</option><option value="APROVADA">Aprovada</option><option value="CANCELADA">Cancelada</option></select></label><label style={{gridColumn:'1 / -1'}}><span>Observações</span><textarea value={m.notes||''} onChange={e=>set('notes',e.target.value)}/></label><div><button className="primary" type="submit"><Save size={18}/>Salvar medição</button></div></form></section>;
}
function UpdateForm({currentProgress,onCancel,onSave}:{currentProgress:number;onCancel:()=>void;onSave:(u:WorkUpdate)=>void}){const [date,setDate]=useState(today());const [text,setText]=useState('');const [progress,setProgress]=useState(currentProgress);const submit=(e:FormEvent)=>{e.preventDefault();if(!text.trim()){alert('Informe a descrição do andamento.');return}onSave({id:Date.now(),date,text:text.trim(),progress:Math.max(0,Math.min(100,progress))})};return <section className="panel" style={{margin:16}}><form onSubmit={submit} className="form-grid"><label><span>Data</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>Avanço físico (%)</span><input type="number" min="0" max="100" value={progress} onChange={e=>setProgress(Number(e.target.value))}/></label><label style={{gridColumn:'1 / -1'}}><span>Descrição do andamento</span><textarea value={text} onChange={e=>setText(e.target.value)} style={{minHeight:90}}/></label><div style={{display:'flex',gap:8}}><button type="button" onClick={onCancel}>Cancelar</button><button className="primary" type="submit"><Save size={17}/>Salvar andamento</button></div></form></section>}
